# Generated by Django 6.0.2 on 2026-02-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=100, unique=True, verbose_name="کلمه"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "کلمه",
                "verbose_name_plural": "کلمات",
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="معنی / تعریف")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ترتیب"),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعریف",
                "verbose_name_plural": "تعاریف",
                "ordering": ["order"],
            },
        ),
    ]
